receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  #memory_limiter:
  #  check_interval: 1s
  #  limit_percentage: 65
  #  spike_limit_percentage: 20

processors:
  batch:

# Alternatively, add additional exporters for the backend of your choice and update the
# pipelines below
exporters:
  debug:
    verbosity: detailed
  otlp:
    # US region
    endpoint: https://otlp.nr-data.net:4317
    # EU region
    #endpoint: https://otlp.eu01.nr-data.net:4317
    headers:
      api-key: NEW_RELIC_LICENSE_KEY
    sending_queue:
      batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
